root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.eslint.json'
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2022
  sourceType: module

extends:
  - eslint:recommended
  - plugin:react/recommended
  - 'plugin:@typescript-eslint/recommended'
  - airbnb-typescript
  - plugin:react/jsx-runtime

plugins:
  - '@typescript-eslint'
  - react
  - import

env:
  browser: true
  es2021: true

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/*.{spec,test}.{ts,tsx}'
        - src/setupTests.ts
